app/urls.py
from django.urls import path
from .views import IndexView, ContactView, AboutView, ServiceView, OurWorksView,submit_form, TestimonialView


app_name = 'app'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('service/', ServiceView.as_view(), name='service'),
    path('our_works/', OurWorksView.as_view(), name='our_works'),
    path('submit/form/', submit_form, name='submit_common_form'),
    path('testimonial/', TestimonialView.as_view(), name='testimonial'),
    path('about/<slug:slug>/', AboutView.as_view(), name='about'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('v1/', include('restful.urls')),
)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restful/urls.py
from django.urls import path
from .views import *
app_name='rest'

urlpatterns = [
    path('send/', SendMessage.as_view(), name='send_message')
]

app/models.py
from django.db import models
from django.urls import reverse
from django.views import generic
from parler.models import TranslatableModel, TranslatedFields
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from filer.fields import image as filer_image


class MainSlider(TranslatableModel):
    translation = TranslatedFields(
        title=models.CharField(max_length=200, null=True, blank=True),
        description=RichTextUploadingField(null=True, blank=True),
    )
    image = models.ImageField(upload_to='media/%Y/%m/d')

    def __str__(self):
        return self.safe_translation_getter('title' or None)


class Testimonial(TranslatableModel):
    translation = TranslatedFields(
        title=models.CharField(max_length=200, blank=True),
        description=RichTextUploadingField(null=True, blank=True),
        position=models.CharField(max_length=200)
    )
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='media/%Y/%m/%d')
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.safe_translation_getter('title')


class AboutCompany(TranslatableModel):
    translation = TranslatedFields(
        title=models.CharField(max_length=200, null=True, blank=True, verbose_name='Title'),
        description=RichTextUploadingField(null=True, blank=True)
    )
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.safe_translation_getter('title' or '')

    class Meta:
        verbose_name = 'About Company'


class Service(TranslatableModel):
    translation = TranslatedFields(
        title=models.CharField(max_length=100, verbose_name='Title'),
        description=RichTextUploadingField(null=True, blank=True)
    )
    image = models.ImageField(upload_to='media', null=True, blank=True)

    def __str__(self):
        return "{}".format(self.safe_translation_getter('title') or '')

    class Meta:
        verbose_name = 'Service'


class ServiceSpecification(TranslatableModel):
    translation = TranslatedFields(
        info=RichTextUploadingField(null=True, blank=True)
    )
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='specification')

    def __str__(self):
        return self.safe_translation_getter('info' or None)


class OurWorks(TranslatableModel):
    translation = TranslatedFields(
        title=models.CharField(max_length=200, blank=True, null=True),
        description=models.TextField(),
    )
    main_image = filer_image.FilerImageField(null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.safe_translation_getter('title' or None)


class OurWorksImages(models.Model):
    our_work = models.ForeignKey(OurWorks, on_delete=models.CASCADE, related_name='image_list')
    image = filer_image.FilerImageField(null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return "{}".format(self.our_work.safe_translation_getter('title'))


class Message(models.Model):
    your_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.your_name

restful/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms
from .models import Message, Service
from django.utils.translation import gettext_lazy as _


class MessageForm(forms.ModelForm):
    message = forms.CharField(required=False)

    class Meta:
        model = Message
        fields = ['your_name', 'phone_number', 'message']
        widgets = {
            'your_name': forms.TextInput({'placeholder': _('Your Name')}),
            'phone_number': forms.TextInput({'placeholder': _('Phone Number')}),
            'message': forms.TextInput({'placeholder': _('Message')}),
        }

app/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .models import Service, Testimonial, MainSlider, OurWorks, AboutCompany
from .forms import MessageForm


class IndexView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['services'] = Service.objects.all()
        context['message_form'] = MessageForm()
        context['testimonials'] = Testimonial.objects.all()
        context['main_slider'] = MainSlider.objects.all()
        context['our_works'] = OurWorks.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        context = {}
        message_form = MessageForm(data=request.POST or None)
        if message_form.is_valid():
            message_form.save()
            messages.success(request=self.request, message=('successfully',))
        else:
            context['message_form'] = MessageForm()
        return render(request, self.template_name, self.get_context_data(**context))


def submit_form(request):
    if request.method == 'POST':
        message_form = MessageForm(data=request.POST or None)
        if message_form.is_valid():
            message_form.save()
            messages.success(request=request, message=('successfully',))
            return redirect(request.META.get('HTTP_REFERER'))
        return redirect(request.META.get('HTTP_REFERER'))


class ContactView(TemplateView):
    template_name = 'contacts.html'


class AboutView(TemplateView):
    template_name = 'about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            about_data = AboutCompany.objects.get(slug=kwargs['slug'])
        except ModuleNotFoundError:
            about_data = {}
        context['about_data'] = about_data
        return context


class ServiceView(TemplateView):
    template_name = 'service.html'


class OurWorksView(TemplateView):
    template_name = 'ourWorks.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['our_works'] = OurWorks.objects.all()
        return context


class TestimonialView(TemplateView):
    template_name = 'testimonials.html'

restful/views.py
from django.template.loader import render_to_string
from rest_framework.response import Response
from rest_framework.views import APIView

from app.models import Message


class SendMessage(APIView):
    def post(self, request):
        data = request.POST.copy()
        message = Message(your_name=data['name'], phone_number=data['phone'])
        message.save()
        html = render_to_string("restful/message.html")
        return Response({'success': html})

templates/about.html
{% extends 'about_main.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'Главная' %}{% endblock title %}

{% block aboutcontent %}
<div class="about__content">
          <div class="about__title">
            <h2>{{ about_data.title }}</h2>
          </div>
              {{ about_data.description|safe }}
              {% if about_data.image %}
                  <div class="about__content-img">
                                    <img src="{{ about_data.image.url }}" alt="">

                  </div>
              {% endif %}
        </div>

{% endblock aboutcontent%}

templates/about_main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="about">
      <div class="about__container container">
              <ul class="about__sidebar">
      {% for about_company_item in about_company %}
          <li>
          {% url 'app:about' slug=about_company_item.slug as about_company_url %}
            <a href="{{ about_company_url }}" {% if about_company_url == request.path %}class="active"{% endif %} >
                {{ about_company_item.title }}</a>
          </li>
      {% endfor %}
        </ul>

          {% block aboutcontent %}
          {% endblock aboutcontent %}


      </div>
    </div>
{% endblock content %}


templates/base.html
{% load i18n %}
{% load static  %}
{% load app_tags %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}">

    <title>{% block title %} home {% endblock title %}</title>
  </head>
  <body>
  <div class="success">
  <div class="success__icon">
    <img src="{% static 'img/icon_tich.png' %}" alt="" />
  </div>
</div>
    <header class="header">
  <div class="header__container">
    <div class="header__top container">
      <div class="header__col logo-col">
            <a href="{% url 'app:home' %}" class="header__logo">
                <img src="{% static '/img/mainLogo.png' %}" alt="mainLogo" />
            </a>
        <div class="header__logo-content">
          <h2>Powerlin</h2>
          <p>{% trans 'Строим будущее вместе' %}</p>
        </div>
      </div>
      <div class="header__col">
        <ul class="header__contact-ul header__contact-ul_tel">
          <li>
            <a href="tel:+99898-362-80-04">+99898-362-80-04</a>
          </li>

            <li>
            <a href="tel:+99871-234-06-73">+99871-234-06-73</a>
          </li>
        </ul>
      </div>
      <div class="header__col">
        <ul class="header__contact-ul header__contact-ul_mail">
          <li>
            <a href="mail:info@powerlin-group.uz">info@powerlin-group.uz</a>
          </li>
        </ul>
      </div>
      <div class="header__col">
        <div class="header__btn">
          <a href="#">{% trans 'Заказать звонок' %}</a>
        </div>
      </div>
      <div class="header__col">
        <div class="hamburger">
          <div class="lines-wrapper">
            <div class="lines line-top"></div>
            <div class="lines line-mid"></div>
            <div class="lines line-bottom"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="header__bottom">
      <div class="header__bottom-wrapper container">
        <nav class="header__menu">
          <ul>
            <li>
              <a href="{% url 'app:home' %}">{% trans 'Главная' %}</a>
            </li>
            <li>
              <a href="{% url 'app:about' slug='o-kompanii' %}">{% trans 'О компании' %}</a>
                <ul class="header__dropdown-ul">
                  {% for about_company_item in about_company %}
                      <li>
                        <a href="{% url 'app:about' slug=about_company_item.slug %}">{{ about_company_item.title }}</a>
                    </li>
                  {% endfor %}
              </ul>
            </li>
            <li>
              <a href="{% url 'app:service' %}">{% trans 'Услуги' %}</a>
              <ul class="header__dropdown-ul">
                  {% for servise in services %}
                    <li>
                      <a href="{% url 'app:service' %}">{{ servise.title }}</a>
                    </li>
                  {% endfor %}
              </ul>
            </li>
            <li>
              <a href="{% url 'app:our_works' %}">{% trans 'Наши Работы' %}</a>
            </li>
            <li>
              <a href="{% url 'app:contact' %}">{% trans 'Контакты' %}</a>
            </li>
          </ul>

        <div class="lang">
                <span class="cur-lang">
                    {{ LANGUAGE_CODE }}
                </span>
                <ul>
                    {% for lang_code, lang_name in LANGUAGES %}
                        <li>
                            {% get_url_tag request=request lang=lang_code as url %}
                            <a href="{{ url }}" >{{ lang_code }}</a>
                        </li>
                    {% endfor %}
                </ul>
        </div>
        </nav>

      </div>
    </div>
  </div>
</header>


{% block content %}
{% endblock content %}
    <!-- footer start -->

    <footer class="footer">
  <div class="footer__container container">
    <div class="footer__col-logo">
          <a href="{% url 'app:home' %}" class="footer__logo">
              <img src="{% static 'img/fooLogo.png' %}" alt="footer logo" />
          </a>
      <div class="footer__col-content">
        <p>{% trans "Строим будущее вместе" %}
        </p>
      </div>
    </div>

    <div class="footer__col">
      <div class="footer__foo-header">
        <h2>{% trans 'Меню' %}</h2>
      </div>
      <ul>
        <li>
            <a href="{% url 'app:home' %}" class="href">{% trans 'главная' %}</a>
        </li>
        <li>
            <a href="{% url 'app:our_works' %}" class="href">{% trans 'Наши работы' %}</a>
        </li>
        <li>
          <a>{% trans 'Отзыв' %}</a>
        </li>
      </ul>
    </div>
    <div class="footer__col">
      <div class="footer__foo-header">
        <h2>{% trans 'Услуги' %}</h2>
      </div>
        {% for service in services %}
            <ul>
                <li>
                    <a href="{% url 'app:service' %}" class="href">{{ service.title }}</a>
                </li>
            </ul>
        {% endfor %}

    </div>
    <div class="footer__col">
      <div class="footer__foo-header">
        <h2>{% trans 'Контакты' %}</h2>
      </div>
      <ul>
        <li>
          <a href="tel:+99898-362-80-04">+99898-362-80-04</a>
        </li>

        <li>
          <a href="mail:info@powerlin-group.uz">info@powerlin-group.uz</a>
        </li>
        <li>
          <a href="tel:Telegram">Telegram</a>
        </li>
      </ul>
    </div>
  </div>
</footer>
    <div class="copyright">
        <div class="container">
            <p>Copyright © 2020 powerlin-group.uz Все права защищены.</p>
            <p>Powered by <a href="http://pixyz.uz">PixYz</a></p>
        </div>
    </div>

  <div class="form-popup">
  <div class="form-block">
    <div class="form-block__content">
      <div class="form-block__title">
        <h2>Powerlin</h2>
      </div>
        <p class="infoo">HHHHHHHsgdfgsdfgsdfgv</p>
      <p class="form-success-content active">
{#        {% trans 'Спасибо, что связались с нами. Один из наших коллег скоро свяжется с вами!' %}#}
      </p>
    </div>
    <form  class="form-block__form" id="common_form">
      <div class="form-block__input">
          <input type="text" placeholder="{% trans 'Ваше имя' %}" id="name">
      </div>
      <div class="form-block__input">
           <input type="text" placeholder="{% trans 'Ваш номер телефона' %}" id="phone">
      </div>
      <div class="form-block__btn">
        <button id="common_form_submit">{% trans 'Заказать звонок' %}</button>
      </div>
    </form>
    <a href="#" class="form-block__close">
      <img src="{% static '/img/formClose.png' %}" alt="" />
    </a>
  </div>
</div>

    <script src="{% static '/js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static '/js/slick.min.js' %}"></script>
    <script src="{% static '/js/anime.js' %}"></script>
    <script src="{% static '/js/dynamic.js' %}"></script>
     <script>
      AOS.init({
        duration: 1000,
      });
    </script>
    <script src="{% static '/js/index.js' %}"></script>
    <!-- Chatra {literal} -->
<script>
        function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            let cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                let cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    window.getCookie = getCookie;
    let csrfToken = window.getCookie('csrftoken');

    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrfToken);
                console.log(csrfToken)
            }
        },
        headers: {
            'Accept-Language': '{{ LANGUAGE_CODE }}',
        }
    });

    $('.form-block__btn').on('click',(e)=>{
        e.preventDefault();
        let name = $('#name').val();
        let phone = $('#phone').val();
        if (name !=='' && phone !==''){
            $.post('{% url 'rest:send_message' %}',{'name':name, 'phone':phone}).done((e)=>{
                console.log(e.success)
                $(".infoo").css("display","none")
                $(".form-success-content").html(e.success)


            setTimeout(function (){
             $(".infoo").css("display","block")
             $(".form-success-content").addClass("active")
            },2500)

            $('#name').val('')
            $('#phone').val('')
            })

        }
        else{
            alert("Formani To'ldiring")
        }

    })



</script>
  <!-- Chatra {literal} -->
<script>
    (function(d, w, c) {
        w.ChatraID = 'aXEPbEp5CTNGNbpGf';
        var s = d.createElement('script');
        w[c] = w[c] || function() {
            (w[c].q = w[c].q || []).push(arguments);
        };
        s.async = true;
        s.src = 'https://call.chatra.io/chatra.js';
        if (d.head) d.head.appendChild(s);
    })(document, window, 'Chatra');
</script>
<!-- /Chatra {/literal} -->
<!-- /Chatra {/literal} -->
  </body>
</html>

templates/contacts.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %} Contact {% endblock title %}

{% block content %}
    <div class="main-contacts">
      <div class="main-contacts__container container">
        <div class="main-contacts__title">
          <h2>контакты</h2>
        </div>

        <div class="main-contacts__items">
          <div class="main-contacts__item">
            <div class="main-contacts__item-title">
              <h2>{% trans 'Адрес' %}</h2>
            </div>
            <div class="main-contacts__item-content">
              <p>{% trans 'г. Ташкент, Юнусабадский район, ул. Чингиза Айтматова 54' %}</p>
            </div>
            <div class="main-contacts__item-icon">
              <img src="{% static '/img/contact1.png' %}" alt="" />
            </div>
          </div>
          <div class="main-contacts__item">
            <div class="main-contacts__item-title">
              <h2>{% trans 'Телефон и Эл. почта:' %}</h2>
            </div>
            <div class="main-contacts__item-content">
              <ul>

                <li class="mai-contacts__mail-li">
                  <a href="tel:+99898-362-80-04"> +99898-362-80-04</a>
                    <br>
                  <a href="tel:+99893-183-80-89"> +99893-183-80-89</a>
                    <br>
                  <a href="tel:+99871-234-06-73"> +99871-234-06-73</a>
                  <li class="mai-contacts__mail-li">
                    <a href="info@powerlin-group.uz">info@powerlin-group.uz</a>
                </li>
                </li>
              </ul>
            </div>
            <div class="main-contacts__item-icon">
              <img src="{% static '/img/contacts2.png' %}" alt="" />
            </div>
          </div>
          <div class="main-contacts__item">
            <div class="main-contacts__item-title">
              <h2>{% trans 'Время работы' %}</h2>
            </div>
            <div class="main-contacts__item-content">
              <ul>
                <li><span>{% trans 'Понедельник - Суббота: ' %}</span>{% trans 'с 9.00 до 17.00' %}</li>
                <li><span>{% trans 'График работы' %}</span> с 9.00 до 17.00</li>
              </ul>
            </div>
            <div class="main-contacts__item-icon">
              <img src="{% static '/img/contacts3.png' %}" alt="" />
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="map">
      <div class="map__container container">
        <iframe
          src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11983.085919174591!2d69.2928697!3d41.3355823!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb6677d6a7387d903!2z0LTQstC10YDQuCBlbHBvcnRhINGC0LDRiNC60LXQvdGC!5e0!3m2!1sru!2s!4v1599632050957!5m2!1sru!2s"
          width="600"
          height="450"
          frameborder="0"
          style="border: 0"
          allowfullscreen=""
          aria-hidden="false"
          tabindex="0"
        ></iframe>
      </div>
    </div>
{% endblock content %}

templates/ourWorks.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Our Work {% endblock title %}

{% block content %}


    <div class="ourWorks">
      <div class="ourWorks__container">
        <div class="our-works__header container">
          <div class="our-works__header-title">
            <h2>{% trans 'ВАША МЕЧТА ЗДЕСЬ' %}</h2>
          </div>
          <div class="our-works__header-content">
            <p>
              Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam
              nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam
              erat, sed diam voluptua. At vero eos et accusam et justo duo
              dolores et ea rebum. Stet clita kasd gubergren, no sea takimata
              sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit
              amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
              invidunt ut labore et dolore magna aliquyam erat, sed diam
              voluptua. At vero eos et accusam et justo duo dolores et ea rebum.
              Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum
              dolor sit amet.
            </p>
          </div>

{#          <div class="ourWorks__items">#}
{#              {% for our_work in our_works%}#}
{#                  <div class="our-works__item-wrapper">#}
{#              <div class="our-works__item">#}
{#                <div class="our-works__item-icon">#}
{#                    {% if our_work.image %}#}
{#                        <img src="{{ our_work.image.url }}" alt="our work" />#}
{#                    {% endif %}#}
{#                </div>#}
{#                <div class="our-works__item-title">#}
{#                  <h2>{{ our_work.title }}</h2>#}
{#                </div>#}
{#                <div class="our-works__item-content">#}
{#                  <ul>#}
{#                    <li>{{ our_work.description }}</li>#}
{#                  </ul>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
{#              {% endfor %}#}

{#                {% for item in our_work.image_list.all %}#}
{#                    <img src="{{ item.image.url }}" alt="">#}
{#                {% endfor %}#}




<div class="ourWorks__items">
{% for our_work in our_works %}
    <div class="our-works__item-wrapper">
                        <div class="our-works__item gallery__item-main">
                    <div class="our-works__item-icon " data-fancybox="{{ our_work.title }}" data-src="{{ our_work.main_image.url     }}">
                            <img src="{{ our_work.main_image.url }}" alt="our work" />
                    </div>
                    <div class="our-works__item-title">
                      <h2>{{ our_work.title }}</h2>
                    </div>
                    <div class="our-works__item-content">
                      <ul>
                        <li>{{ our_work.description }}</li>
                      </ul>
                    </div>
                  </div>
                 <div class="gallery__item-drop drop-gallery">
                {% for item in our_work.image_list.all %}
                  <div class="drop-gallery__item" data-src="{{ item.image.url }}" data-fancybox="{{ our_work.title }}">
                    <img src="{{ item.image.url }}" alt="" />
                    <p>{{ our_work.title }}</p>
                  </div>
                {% endfor %}
                </div>

                </div>
{% endfor %}
</div>

        </div>
      </div>
    </div>

{% endblock content %}



</script>

templates/restful/message.html
{% load i18n %}

{% trans 'Спасибо за вашу заявку, скоро наши сотрудники свяжутся с вами.' %}

<script>
    $(document).ready(function (){
     setTimeout(function(){
        $(".form-popup").removeClass("active");
        $(".form-success-content").text("")
        $(".form-success-content").removeClass("active");

     },2000);})
</script>

templates/service.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %} Service {% endblock title %}

{% block content %}
    <div class="main-services">
      <div class="main-services__container container">
        <div class="main-services__title">
          <h2>{% trans 'Услуги' %}</h2>
        </div>
          {% for service_item in services %}

            <div class="main-services__items">
              <div class="main-services__item">
                <div class="main-services__item-icon">
                  <img src="{{ service_item.image.url }}"}>
                </div>
                <div class="main-services__content">
                  <div class="main-services__content-title">
                    <h2>{{ service_item.title }}</h2>
                  </div>
                  <p>{{ service_item.description|safe }}
                  </p>
                  <ul class="main-services__content-ul">
                    {% for specification in service_item.specification.all %}
                        <li>{{ specification|safe }}</li>
                    {% endfor %}
                  </ul>
                  <div class="main-services__content-btn">
                    <a>{% trans 'Заказать' %}</a>
                  </div>
                </div>
              </div>

          {% endfor %}

        </div>
      </div>
    </div>
{% endblock content %}


templates/testimonials.html
{% extends 'base.html' %}
{% load  static  %}
{% load i18n %}
{% block title %}{% trans testmonials %}{% endblock title %}

{% block content %}
<div class="main-testimonials">
      <div class="main-testimonials__container container">


        <div class="main-testimonials__items">

            {% for testimonial in  testimonials%}

          <div class="testimonials__slider-item-wrapper">
            <div class="testimonials__slider-item">
              <div class="testimonials__item-header">
                <div class="testimonials__item-icon">
                  <img src="{{ testimonial.image.url }}" alt="testimonials" />
                </div>
                <div class="testimonials__item-header-content">
                  <span>{{ testimonial.name }}</span>
                  <p>{{ testimonial.title|safe }}</p>
                </div>
              </div>
              <div class="testimonials__item-body">
                {{ testimonial.description|safe }}
              </div>
            </div>
          </div>
            {% endfor %}
        </div>
      </div>
    </div>

{% endblock content %}